config/routes.rb
Rails.application.routes.draw do
  get "/", to: "homepage#home", as: "root"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/download_pdf', to: 'homepage#download_pdf', as: 'download_pdf'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def home
  end
  def download_pdf
    send_file(
      "#{Rails.root}/app/assets/docs/Fernanda_Gabriela_Braga_Resume.pdf",
      type: "application/pdf",
      disposition: 'inline', # 'inline' if you want to show PDF in the browser instead of downloading it directly
      x_sendfile: true
    )
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController


  def home
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/homepage/home.html.erb
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/devicons/devicon@v2.15.1/devicon.min.css">

<div class="container">
  <div class="row">
    <div class="col-sm-6">
    <section class="welcome">
      <h1 class="welcome-name">Fernanda Gabriela Braga</h1>
      <p class="welcome-text">Frontend and Backend Developer</p>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <section class="about-me">
        <div class="about-me-text">
          <h2 id="features-title"> About me </h2>
          <p id="features-text">
            Hello, nice to meet you!
          </p>
          <p id="features-text">I'm Fernanda Gabriela Braga, a Web Developer
            based in Saskatchewan. From a Materials Engineering and Math/Chemistry
            Teacher to a ton of lines of code.
          </p>
          <p id="features-text">
            I recently graduated from Le Wagon - where I discovered a passion
            for creating cool things from scratch.
          </p>
          <p id="features-text">
            I'm excited to keep improving my skills and bringing ideas to life in the browser with the right company.
          </p>
        </div>
      </section>
    </div>
    <div class="col">
      <section class="about-me">
        <div class="about-me-img">
          <%= image_tag ("avatar.jpeg"), class: "avatar-large", alt: "avatar-large" %>
        </div>
      </section>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <div class="feature-skills">
        <h2 id="features-title"> DevTools </h2>
        <ul class="skills">
          <li>
            <i class="skills-icon devicon-html5-plain"></i>
            <p id="icon-text"> HTML5 </p>
          </li>
          <li>
            <i class="skills-icon fa-brands fa-css3-alt"></i>
            <p id="icon-text"> CSS </p>
          </li>
          <li>
            <i class="skills-icon fa-brands fa-js"></i>
            <p id="icon-text"> JAVASCRIPT </p>
          </li>
          <li>
            <i class="skills-icon devicon-sqlite-plain"></i>
            <p id="icon-text"> SQLITE </p>
          </li>
          <li>
            <i class="skills-icon devicon-ruby-plain"></i>
            <p id="icon-text"> RUBY </p>
          </li>
          <li>
            <i class="skills-icon devicon-rails-plain"></i>
            <p id="icon-text"> RAILS </p>
          </li>
          <li>
            <i class="skills-icon devicon-react-original"></i>
            <p id="icon-text"> REACT </p>
          </li>
          <li>
            <i class="skills-icon devicon-bootstrap-plain"></i>
            <p id="icon-text"> BOOTSTRAP </p>
          </li>
          <li>
            <i class="skills-icon devicon-figma-plain"></i>
            <p id="icon-text"> FIGMA </p>
          </li>
          <li>
            <i class="skills-icon devicon-git-plain"></i>
            <p id="icon-text"> GIT </p>
          </li>
          <li>
            <i class="skills-icon fa-solid fa-terminal"></i>
            <p id="icon-text"> TERMINAL </p>
          </li>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col projects">
      <h2 id="features-title-project">Projects</h2>
      <p class="features-text-projects"> The natural of a portfolio is that: It's always a work in progress </p>
    </div>
    <div class="col">
      <div class="group-cards">

        <div class="card mx-auto">
          <h1 class="card-title">What The Help!</h1>
          <i class="projects-icon fa-solid fa-hand-holding-heart"></i>
          <div class="card-body">
            <p class="card-info">A plataform that connect people willing to assist others and ensure they are guided on every step of the way.</p>
            <div class="btn-group">
              <%=link_to "https://what-the-help.herokuapp.com/", target: :_blank do %>
                <button class="card-btn">View Live</button>
              <%end%>
              <%=link_to "https://github.com/fernandagabrielabraga/what_the_help", target: :_blank do %>
                <button class="card-btn card-git">GitHub</button>
              <%end%>
            </div>
          </div>
        </div>

        <div class="card mx-auto">
          <h1 class="card-title">Weather App</h1>
          <i class="projects-icon fa-solid fa-umbrella"></i>
          <div class="card-body">
            <p class="card-info">A simple, yet fully functional weather app.</p>
            <div class="btn-group">
              <%=link_to "https://cranky-yalow-94baec.netlify.app/", target: :_blank do %>
                <button class="card-btn">View Live</button>
              <%end%>
              <%=link_to "https://github.com/fernandagabrielabraga/weather-app", target: :_blank do %>
                <button class="card-btn card-git">GitHub</button>
              <%end%>
            </div>
          </div>
        </div>

        <div class="card mx-auto">
          <h1 class="card-title">My Dictionary</h1>
          <i class="projects-icon fa-solid fa-book"></i>
          <div class="card-body">
            <p class="card-info">Coming soon... </p>
            <div class="btn-group">
              <button class="card-btn">View Live</button>
              <button class="card-btn card-git">GitHub</button>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <body>
    <head>
      <title>Fernanda Gabriela Braga</title>
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>

      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_pack_tag "application", "data-turbolinks-track": "reload", defer: true %>
    </head>
    <%= render 'shared/navbar' %>
    <%= render "shared/flashes" %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/fernandagabrielabraga"><i class="fab fa-github"></i></a>
    <a href="https://www.linkedin.com/in/fernandagabrielabraga/"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Fernanda Gabriela Braga
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
      <li class="nav-item">
        <%=link_to "https://github.com/fernandagabrielabraga", target: :_blank do %>
          <span class="btn-navbar btn-lg btn-custom">GitHub</span>
        <%end%>
      </li>
      <li class="nav-item">
        <%= link_to "Resume", download_pdf_path(format: :pdf), target: :_blank, :class => "themed_text", class: "btn-navbar btn-lg btn-custom" %>
      </li>
      <li class="nav-item">
        <%=link_to "https://www.linkedin.com/in/fernandagabrielabraga/", target: :_blank do %>
          <span class="btn-navbar btn-lg btn-custom">Linkedin</span>
        <%end%>
      </li>
      </ul>
    </div>
  </div>
</div>